"""
Graphical application to display averages, successes, difficulties, and gains related to
the student's academic results.
"""

import tkinter as tk


class ToolTip:
    """ToolTip to display a description on mouse hover.
    (code generated by copilot)"""

    def __init__(self, widget, text):
        self.widget = widget
        self.text = text
        self.nb_lines = text.count('\n')
        self.tooltip_window = None
        self.widget.bind("<Enter>", self.show_tooltip)
        self.widget.bind("<Leave>", self.hide_tooltip)

    def show_tooltip(self, event):
        "Show the ToolTip"
        x = event.x_root + 10
        if self.nb_lines > 1:
            y = event.y_root - 15 * int(self.nb_lines / 2)
        else:
            y = event.y_root + 10
        self.tooltip_window = tk.Toplevel(self.widget)
        self.tooltip_window.wm_overrideredirect(True)
        self.tooltip_window.wm_geometry(f"+{x}+{y}")
        label = tk.Label(
            self.tooltip_window,
            text=self.text,
            relief="solid",
            borderwidth=1,
            justify="left",
            anchor="w")
        label.pack()

    def hide_tooltip(self, event):  # pylint: disable=unused-argument
        "Hide the ToolTip"
        if self.tooltip_window:
            self.tooltip_window.destroy()
        self.tooltip_window = None


class ClusterBancoFrame(tk.LabelFrame):
    "Frame dedicated to the BANCOS of discipline clusters (in the banco frame)"

    def __init__(self, container, cluster, text='Banco', banco_global=None):
        self.container = container
        self.rules = container.rules
        self.report_card = container.report_card
        super().__init__(container, text=text)  # cluster.name)
        self.pack(fill="both", expand="yes")

        self.labels = []
        if banco_global is True or cluster and self.rules.cluster_is_eligible_for_banco(
                cluster):
            self.write("BANCO!", 'dark green')
        else:
            self.write("no BANCO", None)

    def write(self, text, fg):
        "Write the discipline average"
        self.labels.append(
            tk.Label(
                self,
                text=text,
                anchor='w',
                foreground=fg,
                width=9).pack(
                fill='x'))


class ClusterMoneyFrame(tk.LabelFrame):
    "Frame dedicated to the current gains of discipline clusters (in the gains frame)"

    def __init__(self, container, cluster, text='Gains', money_pool=None):
        self.container = container
        self.rules = container.rules
        self.report_card = container.report_card
        super().__init__(container, text=text)  # cluster.name)
        self.pack(fill="both", expand="yes")

        self.labels = []
        if money_pool is not None:
            self.write(f"{money_pool}€", 'Forest Green')
        else:
            marathon_money = self.rules.get_cluster_marathon_money(cluster)
            if not self.rules.cluster_is_eligible_for_marathon(cluster):
                self.write(f"{marathon_money}€ to earn", None)
            else:
                self.write(f"{marathon_money}€", 'Forest Green')

            boost_money = self.rules.get_cluster_boost_money(cluster)
            if not self.rules.cluster_is_eligible_for_boost(cluster):
                if self.rules.cluster_can_boost_money(cluster):
                    self.write(
                        f"{boost_money}€ to BOOST",
                        None)  # 'dark slate gray')
            else:
                self.write(f"{boost_money}€ of BOOST!", 'Forest Green')

    def write(self, text, fg):
        "Write the discipline average"
        self.labels.append(
            tk.Label(
                self,
                text=text,
                anchor='w',
                foreground=fg,
                width=12).pack(
                fill='x'))


class ShortClusterMoneyFrame(tk.LabelFrame):
    "Narrow frame dedicated to the gains of past discipline clusters (in the gains frame)"

    def __init__(self, container, cluster, text='Gains', money_pool=None):
        self.container = container
        self.rules = container.rules
        self.report_card = container.report_card
        super().__init__(container, text=text)  # cluster.name)
        self.pack(fill="both", expand="yes")

        self.labels = []
        if money_pool is not None:
            self.write(f"{money_pool}€", 'Forest Green')
        else:
            marathon_money = self.rules.get_cluster_marathon_money(cluster)
            if not self.rules.cluster_is_eligible_for_marathon(cluster):
                self.write("0€", 'Red')
            else:
                self.write(f"{marathon_money}€", 'Forest Green')

            boost_money = self.rules.get_cluster_boost_money(cluster)
            if not self.rules.cluster_is_eligible_for_boost(cluster):
                if self.rules.cluster_can_boost_money(cluster):
                    self.write(
                        "0€",
                        'Red')  # 'dark slate gray')
            else:
                self.write(f"{boost_money}€", 'Forest Green')

    def write(self, text, fg):
        "Write the discipline average"
        self.labels.append(
            tk.Label(
                self,
                text=text,
                anchor='w',
                foreground=fg,
                width=3).pack(
                fill='x'))


class SubjectAveragesFrame(tk.Frame):
    "Frame dedicated to discipline averages (in the clusters frame)"

    def __init__(self, container, bg):
        # frame 'average by discipline'
        super().__init__(container, relief=tk.GROOVE, background=bg)
        self.container = container
        self.rules = container.rules
        self.report_card = container.report_card

        self.pack(side=tk.RIGHT)
        self.bg = bg
        self.labels = []

    def write(self, text, fg):
        "Write the discipline average"
        self.labels.append(
            tk.Label(
                self,
                text=text,
                background=self.bg,
                anchor='w',
                foreground=fg,
                width=7).pack(
                fill='x'))


class SubjectsFrame(tk.Frame):
    "Frame dedicated to subjects (in the clusters frame)"

    def __init__(self, container, bg):
        # frame 'report_card'
        super().__init__(container, relief=tk.GROOVE, background=bg)
        self.container = container
        self.rules = container.rules
        self.report_card = container.report_card

        self.pack(side=tk.LEFT)
        self.bg = bg
        self.labels = []

    def write(self, text):
        "Write the subject"
        self.labels.append(
            tk.Label(
                self,
                text=text,
                background=self.bg,
                anchor='e',
                width=25).pack(
                fill='x'))


class ClusterAverageFrame(tk.LabelFrame):
    "Frame dedicated to the averages of discipline clusters (in the averages frame)"

    def __init__(self, container, cluster):
        self.container = container
        self.rules = container.rules
        self.report_card = container.report_card
        # Apply rules on background
        bg = None
        if cluster.average is not None:
            if self.rules.cluster_is_eligible_for_boost(cluster):
                bg = 'Spring Green'
            elif self.rules.cluster_is_eligible_for_marathon(cluster):
                bg = 'Light Green'

            text = f"{cluster.name} : {cluster.average:.2f}/20"
            if cluster.name == 'Retards':
                text = f"{cluster.name} : {cluster.average:.0f}"
        else:
            text = cluster.name
        super().__init__(container, text=text, background=bg)
        self.pack(fill="both", expand="yes")

        # frame 'subjects' and 'grades'
        self.frame_subjects = SubjectsFrame(self, bg)
        self.frame_subject_averages = SubjectAveragesFrame(self, bg)

        for report_card_subject in cluster.subjects:
            self.frame_subjects.write(report_card_subject.name)

            # Apply rules on foreground
            subject_average = cluster.subject_average(
                report_card_subject.name)
            average_fg = None
            if subject_average is not None:
                if self.rules.subject_downgrades_eligible_cluster_for_boost(
                        cluster, subject_average):
                    average_fg = 'FireBrick'
                elif self.rules.subject_downgrades_eligible_cluster_for_marathon(
                        cluster, subject_average):
                    average_fg = 'Red'

                text = f"{subject_average:.2f}/20"
                if report_card_subject.name == 'Retards':
                    text = f"{subject_average:.0f}"
                self.frame_subject_averages.write(text, average_fg)
            else:
                self.frame_subject_averages.write('-', average_fg)


class BancoFrame(tk.Frame):
    "Frame dedicated to the bancos"

    def __init__(self, container, cluster, text='Banco', banco_global=None):
        # frame 'banco by discipline'
        super().__init__(container, relief=tk.GROOVE)
        # self.container = container
        self.rules = container.rules
        self.report_card = container.report_card
        self.cluster_frame = []
        self.cluster_frame.append(
            ClusterBancoFrame(
                self, cluster, text, banco_global))


class MoneyFrame(tk.Frame):
    "Frame dedicated to current gains"

    def __init__(self, container, report_card, cluster, text=None, total_gain=None):
        # frame 'gains'
        super().__init__(container, relief=tk.GROOVE)
        # self.container = container
        self.rules = container.rules
        self.report_card = report_card
        if not text:
            text = report_card.infos.period_name
        self.cluster_frame = []
        self.cluster_frame.append(
            ClusterMoneyFrame(
                self, cluster, text, total_gain))


class ShortMoneyFrame(tk.Frame):
    "Narrow frames dedicated to past gains"

    def __init__(self, container, report_card, cluster, text=None, total_gain=None):
        # frame 'gains'
        super().__init__(container, relief=tk.GROOVE)
        # self.container = container
        self.rules = container.rules
        self.report_card = report_card
        if not text:
            text = report_card.infos.short_period_name
        self.cluster_frame = []
        self.cluster_frame.append(
            ShortClusterMoneyFrame(
                self, cluster, text, total_gain))


class ReportCardFrame(tk.Frame):
    "Frame dedicated to the report card"

    def __init__(self, container, report_card, cluster):
        # frame 'average'
        super().__init__(container, relief=tk.GROOVE)
        # self.container = container
        self.rules = container.rules
        self.report_card = report_card
        self.cluster_frame = []
        self.cluster_frame.append(ClusterAverageFrame(self, cluster))


class HorizontalGauge(tk.Canvas):
    """Code generated by 'Copilot' to create a horizontal gauge"""

    def __init__(self, parent, width=400, height=50):
        super().__init__(parent, width=width, height=height)
        # self.pack()
        self.width = width
        self.height = height
        self.create_rectangle(10, 10, width - 10, height - 10, outline='black')
        self.gauge_bar = self.create_rectangle(
            10, 10, 10, height - 10, fill='green')

        # Create the label with a background color matching the canvas
        self.label = tk.Label(
            self, text="", font=(
                'Arial', 12, 'bold'), bg=self['bg'])
        # Initially placed on the left
        self.label.place(x=10, y=height // 2, anchor='e')

    def set_value(self, value, max_value=100):
        "Set the gauge level"
        if value is None:
            value = 0.0
        ratio = value / max_value
        ratio = min(ratio, 1.0)

        fill_width = 10 + (self.width - 20) * ratio
        # Handle the display of small values and the transition to two digits
        if ratio * 100 < 10.:
            fill_width = max(fill_width, 45)
        else:
            fill_width = max(fill_width, 55)
        self.coords(self.gauge_bar, 10, 10, fill_width, self.height - 10)

        if ratio <= 0.5:
            red = 255
            green = int(2 * ratio * 255)
        else:
            green = 255
            red = int((1 - 2 * (ratio - 0.5)) * 255)
        color = f'#{red:02x}{green:02x}00'

        self.itemconfig(self.gauge_bar, fill=color)

        # Update the label text and its position
        self.label.config(text=f"{int(value / max_value * 100)}%", bg=color)
        self.label.place(x=fill_width, y=self.height // 2, anchor='e')


class BancoSafe(tk.Canvas):
    "Graphical representation of the BANCO"

    def __init__(self, rules, report_card, width, height):
        super().__init__(width=width, height=height)
        self.width = width
        self.height = height

        self.rules = rules
        self.report_card = report_card
        self.banco_rate = self.rules.get_banco_rate(self.report_card)

        self.safe_images = {}
        self.safe_images[0]   = tk.PhotoImage(file="the_school_award\\images\\safe_00%.png")
        self.safe_images[20]  = tk.PhotoImage(file="the_school_award\\images\\safe_20%.png")
        self.safe_images[40]  = tk.PhotoImage(file="the_school_award\\images\\safe_40%.png")
        self.safe_images[60]  = tk.PhotoImage(file="the_school_award\\images\\safe_60%.png")
        self.safe_images[80]  = tk.PhotoImage(file="the_school_award\\images\\safe_80%.png")
        self.safe_images[100] = tk.PhotoImage(file="the_school_award\\images\\safe_100%.png")

        self.images = []
        self.images.append(self.create_image(
            self.width / 2, self.height / 2, image=self.safe_images[self.banco_rate]))


class MoneyPoolFull(tk.Toplevel):
    "Graphical representation of the full money pool"

    def __init__(self, container):
        super().__init__(container)
        self.container = container
        self.title("Congratulations!")

        # Display the festive open safe if the money pool is full
        self.opened_safe_party_image = tk.PhotoImage(
            file="the_school_award\\images\\congratulation.png")
        self.canvas = tk.Canvas(self,
                                width=self.opened_safe_party_image.width(),
                                height=self.opened_safe_party_image.height())
        self.canvas.pack()
        self.images = []
        self.images.append(
            self.canvas.create_image(
                self.opened_safe_party_image.width() / 2,
                self.opened_safe_party_image.height() / 2,
                image=self.opened_safe_party_image))


class Application(tk.Tk):
    "Graphical application"

    def __init__(self, rules, report_cards):
        super().__init__()
        self.rules = rules
        self.report_cards = report_cards
        self.nb_report_cards = len(report_cards)

        self.title('The school award')
        self.resizable(False, False)

        current_column = 1
        self.report_card_frame = []
        self.gains = []
        current_report_card_done = False
        for report_card in self.report_cards[-1::-1]: # Current report card to first one
            current_row = 0
            for cluster in report_card.clusters:
                if not current_report_card_done:
                    report_card_frame = ReportCardFrame(self, report_card, cluster)

                    report_card_frame.grid(
                        row=current_row,
                        column=0,
                        padx=5,
                        pady=5,
                        sticky='n')
                    # Make the frames visible
                    report_card_frame.grid_propagate(False)

                if not current_report_card_done:
                    gains = MoneyFrame(self, report_card, cluster)
                else:
                    gains = ShortMoneyFrame(self, report_card, cluster)
                gains.grid(row=current_row, column=current_column, pady=5, sticky='n')
                # Make the frames visible
                gains.grid_propagate(False)

                self.report_card_frame.append(report_card_frame)
                self.gains.append(gains)
                current_row += 1
            current_column += 1
            current_report_card_done = True

        # Summary
        self.total_gain = 0
        for report_card in self.report_cards:
            self.total_gain += rules.get_report_card_money(report_card)
        gains = MoneyFrame(self, None, None, text='Summary', total_gain=self.total_gain)
        gains.grid(row=current_row, column=1, pady=5, sticky='n', columnspan=self.nb_report_cards)
        gains.grid_propagate(False)
        self.gains.append(gains)

        # Graphical representation of the BANCO
        self.banco_safe_width = 250
        self.banco_safe_height = 450
        self.banco_safe = BancoSafe(
            self.rules,
            self.report_cards[-1],  # Current report card
            self.banco_safe_width,
            self.banco_safe_height)
        self.banco_safe.grid(row=0, column=current_column, rowspan=5, pady=5, sticky='n')
        self.banco_tooltip = ToolTip(
            self.banco_safe,
            self.rules.get_banco_description())

        # Gauge for the reward money pool
        self.target_amount_rate = rules.get_target_amount_rate(
            money_pool=self.total_gain)
        self.target_amount_rate_canvas = HorizontalGauge(
            self, self.banco_safe_width, 49)
        self.target_amount_rate_canvas.set_value(self.target_amount_rate)
        self.target_amount_rate_canvas.grid(
            row=current_row, column=current_column, padx=5, pady=5, sticky='n')
        self.target_amount_rate_canvas.grid_propagate(False)
        self.target_amount_rate_tooltip = ToolTip(
            self.target_amount_rate_canvas,
            self.rules.get_marathon_description() +
            '\n\n' +
            self.rules.get_boost_description())

        # Display the festive open safe if the money pool is full
        if self.target_amount_rate and self.target_amount_rate >= 100:
            self.money_pool = MoneyPoolFull(self)
